documentTitle: A new document
current_iri: http://rs.tdwg.org/ac/doc/termlist/
doc_created: '2013-10-23'
doc_modified: '2022-05-26'
publisher: Biodiversity Information Standards (TDWG)
license_statement: Licensed under a Creative Commons Attribution-ShareAlike 4.0 International
  (CC BY-SA) License.
license_uri: http://creativecommons.org/licenses/by-sa/4.0/
citation: Audubon Core Maintenance Group. 2021. Audubon Core Term List. Biodiversity
  Information Standards (TDWG). http://rs.tdwg.org/ac/doc/termlist/2021-10-05
creator: GBIF/TDWG Multimedia Resources Task Group
comment: ''
accessUrl: https://github.com/tdwg/ac/raw/master/docs/termlist.md
browserRedirectUri: https://tdwg.github.io/ac/termlist/
dcterms_isPartOf: http://www.tdwg.org/standards/638
abstract: The Audubon Core is a set of vocabularies designed to represent metadata
  for biodiversity multimedia resources and collections. It aims to represent information
  that will help to determine whether a particular resource or collection will be
  fit for some particular biodiversity science application before acquiring the media.
  Among others, the vocabularies address such concerns as the management of the media
  and collections, descriptions of their content, their taxonomic, geographic, and
  temporal coverage, and the appropriate ways to retrieve, attribute and reproduce
  them. This document contains a list of attributes of each Audubon Core term, including
  a documentation name, a specified URI, a recommended English label for user interfaces,
  a definition, and some ancillary notes. This document contains normative content
  that may not be changed without due process.
