PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bios: <http://www.github.com/biosemantics/>
SELECT DISTINCT ?text WHERE {
  ?treatment rdf:type bios:Treatment.
  ?treatment (bios:nextCouplet/bios:hasStatement)* ?statement.
  ?statement bios:statementText ?text.
  ?statement (bios:nextCouplet/bios:hasStatement)* ?finalStatement.
  ?finalStatement bios:determination "23 Cucurbita".
}
LIMIT 10