PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bios: <http://www.github.com/biosemantics/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?text WHERE {
  ?treatment rdf:type bios:Treatment.
  ?treatment (bios:nextNode)+ ?statement.
  ?statement rdfs:label ?text.
  ?statement (bios:nextNode)+ ?determination.
  ?determination rdfs:label "Cucurbita".
}
